# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import strategy_pb2 as strategy__pb2

GRPC_GENERATED_VERSION = '1.66.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in strategy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StrategyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EvaluateRules = channel.unary_unary(
                '/strategy.StrategyService/EvaluateRules',
                request_serializer=strategy__pb2.EvaluateRequest.SerializeToString,
                response_deserializer=strategy__pb2.EvaluateResponse.FromString,
                _registered_method=True)
        self.TestRule = channel.unary_unary(
                '/strategy.StrategyService/TestRule',
                request_serializer=strategy__pb2.TestRuleRequest.SerializeToString,
                response_deserializer=strategy__pb2.TestRuleResponse.FromString,
                _registered_method=True)
        self.DetectAnomalies = channel.unary_unary(
                '/strategy.StrategyService/DetectAnomalies',
                request_serializer=strategy__pb2.AnomalyRequest.SerializeToString,
                response_deserializer=strategy__pb2.AnomalyResponse.FromString,
                _registered_method=True)
        self.PredictROI = channel.unary_unary(
                '/strategy.StrategyService/PredictROI',
                request_serializer=strategy__pb2.PredictRequest.SerializeToString,
                response_deserializer=strategy__pb2.PredictResponse.FromString,
                _registered_method=True)
        self.GenerateRecommendations = channel.unary_unary(
                '/strategy.StrategyService/GenerateRecommendations',
                request_serializer=strategy__pb2.RecRequest.SerializeToString,
                response_deserializer=strategy__pb2.RecResponse.FromString,
                _registered_method=True)


class StrategyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EvaluateRules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectAnomalies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictROI(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateRecommendations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StrategyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EvaluateRules': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateRules,
                    request_deserializer=strategy__pb2.EvaluateRequest.FromString,
                    response_serializer=strategy__pb2.EvaluateResponse.SerializeToString,
            ),
            'TestRule': grpc.unary_unary_rpc_method_handler(
                    servicer.TestRule,
                    request_deserializer=strategy__pb2.TestRuleRequest.FromString,
                    response_serializer=strategy__pb2.TestRuleResponse.SerializeToString,
            ),
            'DetectAnomalies': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectAnomalies,
                    request_deserializer=strategy__pb2.AnomalyRequest.FromString,
                    response_serializer=strategy__pb2.AnomalyResponse.SerializeToString,
            ),
            'PredictROI': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictROI,
                    request_deserializer=strategy__pb2.PredictRequest.FromString,
                    response_serializer=strategy__pb2.PredictResponse.SerializeToString,
            ),
            'GenerateRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateRecommendations,
                    request_deserializer=strategy__pb2.RecRequest.FromString,
                    response_serializer=strategy__pb2.RecResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'strategy.StrategyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('strategy.StrategyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StrategyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EvaluateRules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/strategy.StrategyService/EvaluateRules',
            strategy__pb2.EvaluateRequest.SerializeToString,
            strategy__pb2.EvaluateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TestRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/strategy.StrategyService/TestRule',
            strategy__pb2.TestRuleRequest.SerializeToString,
            strategy__pb2.TestRuleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectAnomalies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/strategy.StrategyService/DetectAnomalies',
            strategy__pb2.AnomalyRequest.SerializeToString,
            strategy__pb2.AnomalyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictROI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/strategy.StrategyService/PredictROI',
            strategy__pb2.PredictRequest.SerializeToString,
            strategy__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/strategy.StrategyService/GenerateRecommendations',
            strategy__pb2.RecRequest.SerializeToString,
            strategy__pb2.RecResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
