# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: strategy.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'strategy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0estrategy.proto\x12\x08strategy\"\x9c\x01\n\x07RuleDef\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\naccount_id\x18\x03 \x01(\x03\x12\x12\n\nscope_json\x18\x04 \x01(\t\x12\x16\n\x0e\x63ondition_json\x18\x05 \x01(\t\x12\x13\n\x0b\x61\x63tion_json\x18\x06 \x01(\t\x12\x10\n\x08schedule\x18\x07 \x01(\t\x12\x10\n\x08\x63ooldown\x18\x08 \x01(\t\"U\n\x0f\x45valuateRequest\x12 \n\x05rules\x18\x01 \x03(\x0b\x32\x11.strategy.RuleDef\x12 \n\x03\x61\x64s\x18\x02 \x03(\x0b\x32\x13.strategy.AdContext\"\x85\x01\n\tAdContext\x12\r\n\x05\x61\x64_id\x18\x01 \x01(\x03\x12\x17\n\x0fqianchuan_ad_id\x18\x02 \x01(\x03\x12\x0c\n\x04\x63ost\x18\x03 \x01(\x01\x12\x0b\n\x03roi\x18\x04 \x01(\x01\x12\x0b\n\x03\x63tr\x18\x05 \x01(\x01\x12\x13\n\x0b\x63onversions\x18\x06 \x01(\x03\x12\x13\n\x0bimpressions\x18\x07 \x01(\x03\"t\n\nRuleAction\x12\x0f\n\x07rule_id\x18\x01 \x01(\x03\x12\r\n\x05\x61\x64_id\x18\x02 \x01(\x03\x12\x13\n\x0b\x61\x63tion_type\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\x01\x12\x12\n\nvalue_type\x18\x05 \x01(\t\x12\x0e\n\x06reason\x18\x06 \x01(\t\"9\n\x10\x45valuateResponse\x12%\n\x07\x61\x63tions\x18\x01 \x03(\x0b\x32\x14.strategy.RuleAction\"T\n\x0fTestRuleRequest\x12\x1f\n\x04rule\x18\x01 \x01(\x0b\x32\x11.strategy.RuleDef\x12 \n\x03\x61\x64s\x18\x02 \x03(\x0b\x32\x13.strategy.AdContext\"h\n\x10TestRuleResponse\x12%\n\x07\x61\x63tions\x18\x01 \x03(\x0b\x32\x14.strategy.RuleAction\x12\x15\n\rwould_trigger\x18\x02 \x01(\x08\x12\x16\n\x0etrigger_reason\x18\x03 \x01(\t2\x9c\x01\n\x0fStrategyService\x12\x46\n\rEvaluateRules\x12\x19.strategy.EvaluateRequest\x1a\x1a.strategy.EvaluateResponse\x12\x41\n\x08TestRule\x12\x19.strategy.TestRuleRequest\x1a\x1a.strategy.TestRuleResponseB1Z/github.com/example/qianchuan-saas/grpc/strategyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'strategy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/github.com/example/qianchuan-saas/grpc/strategy'
  _globals['_RULEDEF']._serialized_start=29
  _globals['_RULEDEF']._serialized_end=185
  _globals['_EVALUATEREQUEST']._serialized_start=187
  _globals['_EVALUATEREQUEST']._serialized_end=272
  _globals['_ADCONTEXT']._serialized_start=275
  _globals['_ADCONTEXT']._serialized_end=408
  _globals['_RULEACTION']._serialized_start=410
  _globals['_RULEACTION']._serialized_end=526
  _globals['_EVALUATERESPONSE']._serialized_start=528
  _globals['_EVALUATERESPONSE']._serialized_end=585
  _globals['_TESTRULEREQUEST']._serialized_start=587
  _globals['_TESTRULEREQUEST']._serialized_end=671
  _globals['_TESTRULERESPONSE']._serialized_start=673
  _globals['_TESTRULERESPONSE']._serialized_end=777
  _globals['_STRATEGYSERVICE']._serialized_start=780
  _globals['_STRATEGYSERVICE']._serialized_end=936
# @@protoc_insertion_point(module_scope)
