// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.2
// source: strategy.proto

package strategy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StrategyService_EvaluateRules_FullMethodName           = "/strategy.StrategyService/EvaluateRules"
	StrategyService_TestRule_FullMethodName                = "/strategy.StrategyService/TestRule"
	StrategyService_DetectAnomalies_FullMethodName         = "/strategy.StrategyService/DetectAnomalies"
	StrategyService_PredictROI_FullMethodName              = "/strategy.StrategyService/PredictROI"
	StrategyService_GenerateRecommendations_FullMethodName = "/strategy.StrategyService/GenerateRecommendations"
)

// StrategyServiceClient is the client API for StrategyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StrategyServiceClient interface {
	EvaluateRules(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*EvaluateResponse, error)
	TestRule(ctx context.Context, in *TestRuleRequest, opts ...grpc.CallOption) (*TestRuleResponse, error)
	DetectAnomalies(ctx context.Context, in *AnomalyRequest, opts ...grpc.CallOption) (*AnomalyResponse, error)
	PredictROI(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictResponse, error)
	GenerateRecommendations(ctx context.Context, in *RecRequest, opts ...grpc.CallOption) (*RecResponse, error)
}

type strategyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStrategyServiceClient(cc grpc.ClientConnInterface) StrategyServiceClient {
	return &strategyServiceClient{cc}
}

func (c *strategyServiceClient) EvaluateRules(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*EvaluateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateResponse)
	err := c.cc.Invoke(ctx, StrategyService_EvaluateRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyServiceClient) TestRule(ctx context.Context, in *TestRuleRequest, opts ...grpc.CallOption) (*TestRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestRuleResponse)
	err := c.cc.Invoke(ctx, StrategyService_TestRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyServiceClient) DetectAnomalies(ctx context.Context, in *AnomalyRequest, opts ...grpc.CallOption) (*AnomalyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnomalyResponse)
	err := c.cc.Invoke(ctx, StrategyService_DetectAnomalies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyServiceClient) PredictROI(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PredictResponse)
	err := c.cc.Invoke(ctx, StrategyService_PredictROI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategyServiceClient) GenerateRecommendations(ctx context.Context, in *RecRequest, opts ...grpc.CallOption) (*RecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecResponse)
	err := c.cc.Invoke(ctx, StrategyService_GenerateRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StrategyServiceServer is the server API for StrategyService service.
// All implementations must embed UnimplementedStrategyServiceServer
// for forward compatibility.
type StrategyServiceServer interface {
	EvaluateRules(context.Context, *EvaluateRequest) (*EvaluateResponse, error)
	TestRule(context.Context, *TestRuleRequest) (*TestRuleResponse, error)
	DetectAnomalies(context.Context, *AnomalyRequest) (*AnomalyResponse, error)
	PredictROI(context.Context, *PredictRequest) (*PredictResponse, error)
	GenerateRecommendations(context.Context, *RecRequest) (*RecResponse, error)
	mustEmbedUnimplementedStrategyServiceServer()
}

// UnimplementedStrategyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStrategyServiceServer struct{}

func (UnimplementedStrategyServiceServer) EvaluateRules(context.Context, *EvaluateRequest) (*EvaluateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvaluateRules not implemented")
}
func (UnimplementedStrategyServiceServer) TestRule(context.Context, *TestRuleRequest) (*TestRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TestRule not implemented")
}
func (UnimplementedStrategyServiceServer) DetectAnomalies(context.Context, *AnomalyRequest) (*AnomalyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectAnomalies not implemented")
}
func (UnimplementedStrategyServiceServer) PredictROI(context.Context, *PredictRequest) (*PredictResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PredictROI not implemented")
}
func (UnimplementedStrategyServiceServer) GenerateRecommendations(context.Context, *RecRequest) (*RecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateRecommendations not implemented")
}
func (UnimplementedStrategyServiceServer) mustEmbedUnimplementedStrategyServiceServer() {}
func (UnimplementedStrategyServiceServer) testEmbeddedByValue()                         {}

// UnsafeStrategyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StrategyServiceServer will
// result in compilation errors.
type UnsafeStrategyServiceServer interface {
	mustEmbedUnimplementedStrategyServiceServer()
}

func RegisterStrategyServiceServer(s grpc.ServiceRegistrar, srv StrategyServiceServer) {
	// If the following call panics, it indicates UnimplementedStrategyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StrategyService_ServiceDesc, srv)
}

func _StrategyService_EvaluateRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServiceServer).EvaluateRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategyService_EvaluateRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServiceServer).EvaluateRules(ctx, req.(*EvaluateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategyService_TestRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServiceServer).TestRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategyService_TestRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServiceServer).TestRule(ctx, req.(*TestRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategyService_DetectAnomalies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnomalyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServiceServer).DetectAnomalies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategyService_DetectAnomalies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServiceServer).DetectAnomalies(ctx, req.(*AnomalyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategyService_PredictROI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServiceServer).PredictROI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategyService_PredictROI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServiceServer).PredictROI(ctx, req.(*PredictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategyService_GenerateRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategyServiceServer).GenerateRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategyService_GenerateRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategyServiceServer).GenerateRecommendations(ctx, req.(*RecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StrategyService_ServiceDesc is the grpc.ServiceDesc for StrategyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StrategyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "strategy.StrategyService",
	HandlerType: (*StrategyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EvaluateRules",
			Handler:    _StrategyService_EvaluateRules_Handler,
		},
		{
			MethodName: "TestRule",
			Handler:    _StrategyService_TestRule_Handler,
		},
		{
			MethodName: "DetectAnomalies",
			Handler:    _StrategyService_DetectAnomalies_Handler,
		},
		{
			MethodName: "PredictROI",
			Handler:    _StrategyService_PredictROI_Handler,
		},
		{
			MethodName: "GenerateRecommendations",
			Handler:    _StrategyService_GenerateRecommendations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "strategy.proto",
}
