// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: strategy.proto

package strategy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuleDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AccountId     int64                  `protobuf:"varint,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ScopeJson     string                 `protobuf:"bytes,4,opt,name=scope_json,json=scopeJson,proto3" json:"scope_json,omitempty"`
	ConditionJson string                 `protobuf:"bytes,5,opt,name=condition_json,json=conditionJson,proto3" json:"condition_json,omitempty"`
	ActionJson    string                 `protobuf:"bytes,6,opt,name=action_json,json=actionJson,proto3" json:"action_json,omitempty"`
	Schedule      string                 `protobuf:"bytes,7,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Cooldown      string                 `protobuf:"bytes,8,opt,name=cooldown,proto3" json:"cooldown,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleDef) Reset() {
	*x = RuleDef{}
	mi := &file_strategy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleDef) ProtoMessage() {}

func (x *RuleDef) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleDef.ProtoReflect.Descriptor instead.
func (*RuleDef) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{0}
}

func (x *RuleDef) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RuleDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuleDef) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *RuleDef) GetScopeJson() string {
	if x != nil {
		return x.ScopeJson
	}
	return ""
}

func (x *RuleDef) GetConditionJson() string {
	if x != nil {
		return x.ConditionJson
	}
	return ""
}

func (x *RuleDef) GetActionJson() string {
	if x != nil {
		return x.ActionJson
	}
	return ""
}

func (x *RuleDef) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *RuleDef) GetCooldown() string {
	if x != nil {
		return x.Cooldown
	}
	return ""
}

type EvaluateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*RuleDef             `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	Ads           []*AdContext           `protobuf:"bytes,2,rep,name=ads,proto3" json:"ads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateRequest) Reset() {
	*x = EvaluateRequest{}
	mi := &file_strategy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRequest) ProtoMessage() {}

func (x *EvaluateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRequest.ProtoReflect.Descriptor instead.
func (*EvaluateRequest) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{1}
}

func (x *EvaluateRequest) GetRules() []*RuleDef {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *EvaluateRequest) GetAds() []*AdContext {
	if x != nil {
		return x.Ads
	}
	return nil
}

type AdContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdId          int64                  `protobuf:"varint,1,opt,name=ad_id,json=adId,proto3" json:"ad_id,omitempty"`
	QianchuanAdId int64                  `protobuf:"varint,2,opt,name=qianchuan_ad_id,json=qianchuanAdId,proto3" json:"qianchuan_ad_id,omitempty"`
	Cost          float64                `protobuf:"fixed64,3,opt,name=cost,proto3" json:"cost,omitempty"`
	Roi           float64                `protobuf:"fixed64,4,opt,name=roi,proto3" json:"roi,omitempty"`
	Ctr           float64                `protobuf:"fixed64,5,opt,name=ctr,proto3" json:"ctr,omitempty"`
	Conversions   int64                  `protobuf:"varint,6,opt,name=conversions,proto3" json:"conversions,omitempty"`
	Impressions   int64                  `protobuf:"varint,7,opt,name=impressions,proto3" json:"impressions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdContext) Reset() {
	*x = AdContext{}
	mi := &file_strategy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdContext) ProtoMessage() {}

func (x *AdContext) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdContext.ProtoReflect.Descriptor instead.
func (*AdContext) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{2}
}

func (x *AdContext) GetAdId() int64 {
	if x != nil {
		return x.AdId
	}
	return 0
}

func (x *AdContext) GetQianchuanAdId() int64 {
	if x != nil {
		return x.QianchuanAdId
	}
	return 0
}

func (x *AdContext) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *AdContext) GetRoi() float64 {
	if x != nil {
		return x.Roi
	}
	return 0
}

func (x *AdContext) GetCtr() float64 {
	if x != nil {
		return x.Ctr
	}
	return 0
}

func (x *AdContext) GetConversions() int64 {
	if x != nil {
		return x.Conversions
	}
	return 0
}

func (x *AdContext) GetImpressions() int64 {
	if x != nil {
		return x.Impressions
	}
	return 0
}

type RuleAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        int64                  `protobuf:"varint,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	AdId          int64                  `protobuf:"varint,2,opt,name=ad_id,json=adId,proto3" json:"ad_id,omitempty"`
	ActionType    string                 `protobuf:"bytes,3,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	Value         float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	ValueType     string                 `protobuf:"bytes,5,opt,name=value_type,json=valueType,proto3" json:"value_type,omitempty"`
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleAction) Reset() {
	*x = RuleAction{}
	mi := &file_strategy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleAction) ProtoMessage() {}

func (x *RuleAction) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleAction.ProtoReflect.Descriptor instead.
func (*RuleAction) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{3}
}

func (x *RuleAction) GetRuleId() int64 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

func (x *RuleAction) GetAdId() int64 {
	if x != nil {
		return x.AdId
	}
	return 0
}

func (x *RuleAction) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *RuleAction) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *RuleAction) GetValueType() string {
	if x != nil {
		return x.ValueType
	}
	return ""
}

func (x *RuleAction) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type EvaluateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []*RuleAction          `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateResponse) Reset() {
	*x = EvaluateResponse{}
	mi := &file_strategy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateResponse) ProtoMessage() {}

func (x *EvaluateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateResponse.ProtoReflect.Descriptor instead.
func (*EvaluateResponse) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{4}
}

func (x *EvaluateResponse) GetActions() []*RuleAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

type TestRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *RuleDef               `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	Ads           []*AdContext           `protobuf:"bytes,2,rep,name=ads,proto3" json:"ads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestRuleRequest) Reset() {
	*x = TestRuleRequest{}
	mi := &file_strategy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRuleRequest) ProtoMessage() {}

func (x *TestRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRuleRequest.ProtoReflect.Descriptor instead.
func (*TestRuleRequest) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{5}
}

func (x *TestRuleRequest) GetRule() *RuleDef {
	if x != nil {
		return x.Rule
	}
	return nil
}

func (x *TestRuleRequest) GetAds() []*AdContext {
	if x != nil {
		return x.Ads
	}
	return nil
}

type TestRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []*RuleAction          `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	WouldTrigger  bool                   `protobuf:"varint,2,opt,name=would_trigger,json=wouldTrigger,proto3" json:"would_trigger,omitempty"`
	TriggerReason string                 `protobuf:"bytes,3,opt,name=trigger_reason,json=triggerReason,proto3" json:"trigger_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestRuleResponse) Reset() {
	*x = TestRuleResponse{}
	mi := &file_strategy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRuleResponse) ProtoMessage() {}

func (x *TestRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRuleResponse.ProtoReflect.Descriptor instead.
func (*TestRuleResponse) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{6}
}

func (x *TestRuleResponse) GetActions() []*RuleAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *TestRuleResponse) GetWouldTrigger() bool {
	if x != nil {
		return x.WouldTrigger
	}
	return false
}

func (x *TestRuleResponse) GetTriggerReason() string {
	if x != nil {
		return x.TriggerReason
	}
	return ""
}

var File_strategy_proto protoreflect.FileDescriptor

const file_strategy_proto_rawDesc = "" +
	"\n" +
	"\x0estrategy.proto\x12\bstrategy\"\xeb\x01\n" +
	"\aRuleDef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\x03R\taccountId\x12\x1d\n" +
	"\n" +
	"scope_json\x18\x04 \x01(\tR\tscopeJson\x12%\n" +
	"\x0econdition_json\x18\x05 \x01(\tR\rconditionJson\x12\x1f\n" +
	"\vaction_json\x18\x06 \x01(\tR\n" +
	"actionJson\x12\x1a\n" +
	"\bschedule\x18\a \x01(\tR\bschedule\x12\x1a\n" +
	"\bcooldown\x18\b \x01(\tR\bcooldown\"a\n" +
	"\x0fEvaluateRequest\x12'\n" +
	"\x05rules\x18\x01 \x03(\v2\x11.strategy.RuleDefR\x05rules\x12%\n" +
	"\x03ads\x18\x02 \x03(\v2\x13.strategy.AdContextR\x03ads\"\xc4\x01\n" +
	"\tAdContext\x12\x13\n" +
	"\x05ad_id\x18\x01 \x01(\x03R\x04adId\x12&\n" +
	"\x0fqianchuan_ad_id\x18\x02 \x01(\x03R\rqianchuanAdId\x12\x12\n" +
	"\x04cost\x18\x03 \x01(\x01R\x04cost\x12\x10\n" +
	"\x03roi\x18\x04 \x01(\x01R\x03roi\x12\x10\n" +
	"\x03ctr\x18\x05 \x01(\x01R\x03ctr\x12 \n" +
	"\vconversions\x18\x06 \x01(\x03R\vconversions\x12 \n" +
	"\vimpressions\x18\a \x01(\x03R\vimpressions\"\xa8\x01\n" +
	"\n" +
	"RuleAction\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\x03R\x06ruleId\x12\x13\n" +
	"\x05ad_id\x18\x02 \x01(\x03R\x04adId\x12\x1f\n" +
	"\vaction_type\x18\x03 \x01(\tR\n" +
	"actionType\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\x12\x1d\n" +
	"\n" +
	"value_type\x18\x05 \x01(\tR\tvalueType\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\"B\n" +
	"\x10EvaluateResponse\x12.\n" +
	"\aactions\x18\x01 \x03(\v2\x14.strategy.RuleActionR\aactions\"_\n" +
	"\x0fTestRuleRequest\x12%\n" +
	"\x04rule\x18\x01 \x01(\v2\x11.strategy.RuleDefR\x04rule\x12%\n" +
	"\x03ads\x18\x02 \x03(\v2\x13.strategy.AdContextR\x03ads\"\x8e\x01\n" +
	"\x10TestRuleResponse\x12.\n" +
	"\aactions\x18\x01 \x03(\v2\x14.strategy.RuleActionR\aactions\x12#\n" +
	"\rwould_trigger\x18\x02 \x01(\bR\fwouldTrigger\x12%\n" +
	"\x0etrigger_reason\x18\x03 \x01(\tR\rtriggerReason2\x9c\x01\n" +
	"\x0fStrategyService\x12F\n" +
	"\rEvaluateRules\x12\x19.strategy.EvaluateRequest\x1a\x1a.strategy.EvaluateResponse\x12A\n" +
	"\bTestRule\x12\x19.strategy.TestRuleRequest\x1a\x1a.strategy.TestRuleResponseB1Z/github.com/example/qianchuan-saas/grpc/strategyb\x06proto3"

var (
	file_strategy_proto_rawDescOnce sync.Once
	file_strategy_proto_rawDescData []byte
)

func file_strategy_proto_rawDescGZIP() []byte {
	file_strategy_proto_rawDescOnce.Do(func() {
		file_strategy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_strategy_proto_rawDesc), len(file_strategy_proto_rawDesc)))
	})
	return file_strategy_proto_rawDescData
}

var file_strategy_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_strategy_proto_goTypes = []any{
	(*RuleDef)(nil),          // 0: strategy.RuleDef
	(*EvaluateRequest)(nil),  // 1: strategy.EvaluateRequest
	(*AdContext)(nil),        // 2: strategy.AdContext
	(*RuleAction)(nil),       // 3: strategy.RuleAction
	(*EvaluateResponse)(nil), // 4: strategy.EvaluateResponse
	(*TestRuleRequest)(nil),  // 5: strategy.TestRuleRequest
	(*TestRuleResponse)(nil), // 6: strategy.TestRuleResponse
}
var file_strategy_proto_depIdxs = []int32{
	0, // 0: strategy.EvaluateRequest.rules:type_name -> strategy.RuleDef
	2, // 1: strategy.EvaluateRequest.ads:type_name -> strategy.AdContext
	3, // 2: strategy.EvaluateResponse.actions:type_name -> strategy.RuleAction
	0, // 3: strategy.TestRuleRequest.rule:type_name -> strategy.RuleDef
	2, // 4: strategy.TestRuleRequest.ads:type_name -> strategy.AdContext
	3, // 5: strategy.TestRuleResponse.actions:type_name -> strategy.RuleAction
	1, // 6: strategy.StrategyService.EvaluateRules:input_type -> strategy.EvaluateRequest
	5, // 7: strategy.StrategyService.TestRule:input_type -> strategy.TestRuleRequest
	4, // 8: strategy.StrategyService.EvaluateRules:output_type -> strategy.EvaluateResponse
	6, // 9: strategy.StrategyService.TestRule:output_type -> strategy.TestRuleResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_strategy_proto_init() }
func file_strategy_proto_init() {
	if File_strategy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_strategy_proto_rawDesc), len(file_strategy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_strategy_proto_goTypes,
		DependencyIndexes: file_strategy_proto_depIdxs,
		MessageInfos:      file_strategy_proto_msgTypes,
	}.Build()
	File_strategy_proto = out.File
	file_strategy_proto_goTypes = nil
	file_strategy_proto_depIdxs = nil
}
