// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: strategy.proto

package strategy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuleDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AccountId     int64                  `protobuf:"varint,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ScopeJson     string                 `protobuf:"bytes,4,opt,name=scope_json,json=scopeJson,proto3" json:"scope_json,omitempty"`
	ConditionJson string                 `protobuf:"bytes,5,opt,name=condition_json,json=conditionJson,proto3" json:"condition_json,omitempty"`
	ActionJson    string                 `protobuf:"bytes,6,opt,name=action_json,json=actionJson,proto3" json:"action_json,omitempty"`
	Schedule      string                 `protobuf:"bytes,7,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Cooldown      string                 `protobuf:"bytes,8,opt,name=cooldown,proto3" json:"cooldown,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleDef) Reset() {
	*x = RuleDef{}
	mi := &file_strategy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleDef) ProtoMessage() {}

func (x *RuleDef) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleDef.ProtoReflect.Descriptor instead.
func (*RuleDef) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{0}
}

func (x *RuleDef) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RuleDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuleDef) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *RuleDef) GetScopeJson() string {
	if x != nil {
		return x.ScopeJson
	}
	return ""
}

func (x *RuleDef) GetConditionJson() string {
	if x != nil {
		return x.ConditionJson
	}
	return ""
}

func (x *RuleDef) GetActionJson() string {
	if x != nil {
		return x.ActionJson
	}
	return ""
}

func (x *RuleDef) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *RuleDef) GetCooldown() string {
	if x != nil {
		return x.Cooldown
	}
	return ""
}

type EvaluateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*RuleDef             `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	Ads           []*AdContext           `protobuf:"bytes,2,rep,name=ads,proto3" json:"ads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateRequest) Reset() {
	*x = EvaluateRequest{}
	mi := &file_strategy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRequest) ProtoMessage() {}

func (x *EvaluateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRequest.ProtoReflect.Descriptor instead.
func (*EvaluateRequest) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{1}
}

func (x *EvaluateRequest) GetRules() []*RuleDef {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *EvaluateRequest) GetAds() []*AdContext {
	if x != nil {
		return x.Ads
	}
	return nil
}

type AdContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdId          int64                  `protobuf:"varint,1,opt,name=ad_id,json=adId,proto3" json:"ad_id,omitempty"`
	QianchuanAdId int64                  `protobuf:"varint,2,opt,name=qianchuan_ad_id,json=qianchuanAdId,proto3" json:"qianchuan_ad_id,omitempty"`
	Cost          float64                `protobuf:"fixed64,3,opt,name=cost,proto3" json:"cost,omitempty"`
	Roi           float64                `protobuf:"fixed64,4,opt,name=roi,proto3" json:"roi,omitempty"`
	Ctr           float64                `protobuf:"fixed64,5,opt,name=ctr,proto3" json:"ctr,omitempty"`
	Conversions   int64                  `protobuf:"varint,6,opt,name=conversions,proto3" json:"conversions,omitempty"`
	Impressions   int64                  `protobuf:"varint,7,opt,name=impressions,proto3" json:"impressions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdContext) Reset() {
	*x = AdContext{}
	mi := &file_strategy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdContext) ProtoMessage() {}

func (x *AdContext) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdContext.ProtoReflect.Descriptor instead.
func (*AdContext) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{2}
}

func (x *AdContext) GetAdId() int64 {
	if x != nil {
		return x.AdId
	}
	return 0
}

func (x *AdContext) GetQianchuanAdId() int64 {
	if x != nil {
		return x.QianchuanAdId
	}
	return 0
}

func (x *AdContext) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *AdContext) GetRoi() float64 {
	if x != nil {
		return x.Roi
	}
	return 0
}

func (x *AdContext) GetCtr() float64 {
	if x != nil {
		return x.Ctr
	}
	return 0
}

func (x *AdContext) GetConversions() int64 {
	if x != nil {
		return x.Conversions
	}
	return 0
}

func (x *AdContext) GetImpressions() int64 {
	if x != nil {
		return x.Impressions
	}
	return 0
}

type RuleAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        int64                  `protobuf:"varint,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	AdId          int64                  `protobuf:"varint,2,opt,name=ad_id,json=adId,proto3" json:"ad_id,omitempty"`
	ActionType    string                 `protobuf:"bytes,3,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	Value         float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	ValueType     string                 `protobuf:"bytes,5,opt,name=value_type,json=valueType,proto3" json:"value_type,omitempty"`
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleAction) Reset() {
	*x = RuleAction{}
	mi := &file_strategy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleAction) ProtoMessage() {}

func (x *RuleAction) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleAction.ProtoReflect.Descriptor instead.
func (*RuleAction) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{3}
}

func (x *RuleAction) GetRuleId() int64 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

func (x *RuleAction) GetAdId() int64 {
	if x != nil {
		return x.AdId
	}
	return 0
}

func (x *RuleAction) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *RuleAction) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *RuleAction) GetValueType() string {
	if x != nil {
		return x.ValueType
	}
	return ""
}

func (x *RuleAction) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type EvaluateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []*RuleAction          `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateResponse) Reset() {
	*x = EvaluateResponse{}
	mi := &file_strategy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateResponse) ProtoMessage() {}

func (x *EvaluateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateResponse.ProtoReflect.Descriptor instead.
func (*EvaluateResponse) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{4}
}

func (x *EvaluateResponse) GetActions() []*RuleAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

type TestRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *RuleDef               `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	Ads           []*AdContext           `protobuf:"bytes,2,rep,name=ads,proto3" json:"ads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestRuleRequest) Reset() {
	*x = TestRuleRequest{}
	mi := &file_strategy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRuleRequest) ProtoMessage() {}

func (x *TestRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRuleRequest.ProtoReflect.Descriptor instead.
func (*TestRuleRequest) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{5}
}

func (x *TestRuleRequest) GetRule() *RuleDef {
	if x != nil {
		return x.Rule
	}
	return nil
}

func (x *TestRuleRequest) GetAds() []*AdContext {
	if x != nil {
		return x.Ads
	}
	return nil
}

type TestRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []*RuleAction          `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	WouldTrigger  bool                   `protobuf:"varint,2,opt,name=would_trigger,json=wouldTrigger,proto3" json:"would_trigger,omitempty"`
	TriggerReason string                 `protobuf:"bytes,3,opt,name=trigger_reason,json=triggerReason,proto3" json:"trigger_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestRuleResponse) Reset() {
	*x = TestRuleResponse{}
	mi := &file_strategy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRuleResponse) ProtoMessage() {}

func (x *TestRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRuleResponse.ProtoReflect.Descriptor instead.
func (*TestRuleResponse) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{6}
}

func (x *TestRuleResponse) GetActions() []*RuleAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *TestRuleResponse) GetWouldTrigger() bool {
	if x != nil {
		return x.WouldTrigger
	}
	return false
}

func (x *TestRuleResponse) GetTriggerReason() string {
	if x != nil {
		return x.TriggerReason
	}
	return ""
}

type AdMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdId          int64                  `protobuf:"varint,1,opt,name=ad_id,json=adId,proto3" json:"ad_id,omitempty"`
	Cost          float64                `protobuf:"fixed64,2,opt,name=cost,proto3" json:"cost,omitempty"`
	Roi           float64                `protobuf:"fixed64,3,opt,name=roi,proto3" json:"roi,omitempty"`
	Ctr           float64                `protobuf:"fixed64,4,opt,name=ctr,proto3" json:"ctr,omitempty"`
	Conversions   int64                  `protobuf:"varint,5,opt,name=conversions,proto3" json:"conversions,omitempty"`
	Impressions   int64                  `protobuf:"varint,6,opt,name=impressions,proto3" json:"impressions,omitempty"`
	Cpa           float64                `protobuf:"fixed64,7,opt,name=cpa,proto3" json:"cpa,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdMetrics) Reset() {
	*x = AdMetrics{}
	mi := &file_strategy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdMetrics) ProtoMessage() {}

func (x *AdMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdMetrics.ProtoReflect.Descriptor instead.
func (*AdMetrics) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{7}
}

func (x *AdMetrics) GetAdId() int64 {
	if x != nil {
		return x.AdId
	}
	return 0
}

func (x *AdMetrics) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *AdMetrics) GetRoi() float64 {
	if x != nil {
		return x.Roi
	}
	return 0
}

func (x *AdMetrics) GetCtr() float64 {
	if x != nil {
		return x.Ctr
	}
	return 0
}

func (x *AdMetrics) GetConversions() int64 {
	if x != nil {
		return x.Conversions
	}
	return 0
}

func (x *AdMetrics) GetImpressions() int64 {
	if x != nil {
		return x.Impressions
	}
	return 0
}

func (x *AdMetrics) GetCpa() float64 {
	if x != nil {
		return x.Cpa
	}
	return 0
}

type MetricsWindow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hourly        []*AdMetrics           `protobuf:"bytes,1,rep,name=hourly,proto3" json:"hourly,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsWindow) Reset() {
	*x = MetricsWindow{}
	mi := &file_strategy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsWindow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsWindow) ProtoMessage() {}

func (x *MetricsWindow) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsWindow.ProtoReflect.Descriptor instead.
func (*MetricsWindow) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{8}
}

func (x *MetricsWindow) GetHourly() []*AdMetrics {
	if x != nil {
		return x.Hourly
	}
	return nil
}

type AnomalyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Current       []*AdMetrics           `protobuf:"bytes,1,rep,name=current,proto3" json:"current,omitempty"`
	History       []*MetricsWindow       `protobuf:"bytes,2,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnomalyRequest) Reset() {
	*x = AnomalyRequest{}
	mi := &file_strategy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnomalyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnomalyRequest) ProtoMessage() {}

func (x *AnomalyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnomalyRequest.ProtoReflect.Descriptor instead.
func (*AnomalyRequest) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{9}
}

func (x *AnomalyRequest) GetCurrent() []*AdMetrics {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *AnomalyRequest) GetHistory() []*MetricsWindow {
	if x != nil {
		return x.History
	}
	return nil
}

type Anomaly struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdId          int64                  `protobuf:"varint,1,opt,name=ad_id,json=adId,proto3" json:"ad_id,omitempty"`
	MetricName    string                 `protobuf:"bytes,2,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	CurrentValue  float64                `protobuf:"fixed64,3,opt,name=current_value,json=currentValue,proto3" json:"current_value,omitempty"`
	MeanValue     float64                `protobuf:"fixed64,4,opt,name=mean_value,json=meanValue,proto3" json:"mean_value,omitempty"`
	StdValue      float64                `protobuf:"fixed64,5,opt,name=std_value,json=stdValue,proto3" json:"std_value,omitempty"`
	ZScore        float64                `protobuf:"fixed64,6,opt,name=z_score,json=zScore,proto3" json:"z_score,omitempty"`
	Severity      string                 `protobuf:"bytes,7,opt,name=severity,proto3" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Anomaly) Reset() {
	*x = Anomaly{}
	mi := &file_strategy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Anomaly) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Anomaly) ProtoMessage() {}

func (x *Anomaly) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Anomaly.ProtoReflect.Descriptor instead.
func (*Anomaly) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{10}
}

func (x *Anomaly) GetAdId() int64 {
	if x != nil {
		return x.AdId
	}
	return 0
}

func (x *Anomaly) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *Anomaly) GetCurrentValue() float64 {
	if x != nil {
		return x.CurrentValue
	}
	return 0
}

func (x *Anomaly) GetMeanValue() float64 {
	if x != nil {
		return x.MeanValue
	}
	return 0
}

func (x *Anomaly) GetStdValue() float64 {
	if x != nil {
		return x.StdValue
	}
	return 0
}

func (x *Anomaly) GetZScore() float64 {
	if x != nil {
		return x.ZScore
	}
	return 0
}

func (x *Anomaly) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

type AnomalyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Anomalies     []*Anomaly             `protobuf:"bytes,1,rep,name=anomalies,proto3" json:"anomalies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnomalyResponse) Reset() {
	*x = AnomalyResponse{}
	mi := &file_strategy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnomalyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnomalyResponse) ProtoMessage() {}

func (x *AnomalyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnomalyResponse.ProtoReflect.Descriptor instead.
func (*AnomalyResponse) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{11}
}

func (x *AnomalyResponse) GetAnomalies() []*Anomaly {
	if x != nil {
		return x.Anomalies
	}
	return nil
}

type PredictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdId          int64                  `protobuf:"varint,1,opt,name=ad_id,json=adId,proto3" json:"ad_id,omitempty"`
	History_7D    []*AdMetrics           `protobuf:"bytes,2,rep,name=history_7d,json=history7d,proto3" json:"history_7d,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	mi := &file_strategy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{12}
}

func (x *PredictRequest) GetAdId() int64 {
	if x != nil {
		return x.AdId
	}
	return 0
}

func (x *PredictRequest) GetHistory_7D() []*AdMetrics {
	if x != nil {
		return x.History_7D
	}
	return nil
}

type ROIPrediction struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AdId             int64                  `protobuf:"varint,1,opt,name=ad_id,json=adId,proto3" json:"ad_id,omitempty"`
	PredictedRoi_24H float64                `protobuf:"fixed64,2,opt,name=predicted_roi_24h,json=predictedRoi24h,proto3" json:"predicted_roi_24h,omitempty"`
	Confidence       float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Trend            string                 `protobuf:"bytes,4,opt,name=trend,proto3" json:"trend,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ROIPrediction) Reset() {
	*x = ROIPrediction{}
	mi := &file_strategy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ROIPrediction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ROIPrediction) ProtoMessage() {}

func (x *ROIPrediction) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ROIPrediction.ProtoReflect.Descriptor instead.
func (*ROIPrediction) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{13}
}

func (x *ROIPrediction) GetAdId() int64 {
	if x != nil {
		return x.AdId
	}
	return 0
}

func (x *ROIPrediction) GetPredictedRoi_24H() float64 {
	if x != nil {
		return x.PredictedRoi_24H
	}
	return 0
}

func (x *ROIPrediction) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ROIPrediction) GetTrend() string {
	if x != nil {
		return x.Trend
	}
	return ""
}

type PredictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Predictions   []*ROIPrediction       `protobuf:"bytes,1,rep,name=predictions,proto3" json:"predictions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictResponse) Reset() {
	*x = PredictResponse{}
	mi := &file_strategy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictResponse) ProtoMessage() {}

func (x *PredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictResponse.ProtoReflect.Descriptor instead.
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{14}
}

func (x *PredictResponse) GetPredictions() []*ROIPrediction {
	if x != nil {
		return x.Predictions
	}
	return nil
}

type RecRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AdIds          []int64                `protobuf:"varint,1,rep,packed,name=ad_ids,json=adIds,proto3" json:"ad_ids,omitempty"`
	CurrentMetrics []*AdMetrics           `protobuf:"bytes,2,rep,name=current_metrics,json=currentMetrics,proto3" json:"current_metrics,omitempty"`
	History_7D     []*MetricsWindow       `protobuf:"bytes,3,rep,name=history_7d,json=history7d,proto3" json:"history_7d,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecRequest) Reset() {
	*x = RecRequest{}
	mi := &file_strategy_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecRequest) ProtoMessage() {}

func (x *RecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecRequest.ProtoReflect.Descriptor instead.
func (*RecRequest) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{15}
}

func (x *RecRequest) GetAdIds() []int64 {
	if x != nil {
		return x.AdIds
	}
	return nil
}

func (x *RecRequest) GetCurrentMetrics() []*AdMetrics {
	if x != nil {
		return x.CurrentMetrics
	}
	return nil
}

func (x *RecRequest) GetHistory_7D() []*MetricsWindow {
	if x != nil {
		return x.History_7D
	}
	return nil
}

type Recommendation struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AdId                int64                  `protobuf:"varint,1,opt,name=ad_id,json=adId,proto3" json:"ad_id,omitempty"`
	Type                string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title               string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description         string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Confidence          float64                `protobuf:"fixed64,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	SuggestedActionJson string                 `protobuf:"bytes,6,opt,name=suggested_action_json,json=suggestedActionJson,proto3" json:"suggested_action_json,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Recommendation) Reset() {
	*x = Recommendation{}
	mi := &file_strategy_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recommendation) ProtoMessage() {}

func (x *Recommendation) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recommendation.ProtoReflect.Descriptor instead.
func (*Recommendation) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{16}
}

func (x *Recommendation) GetAdId() int64 {
	if x != nil {
		return x.AdId
	}
	return 0
}

func (x *Recommendation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Recommendation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Recommendation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Recommendation) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Recommendation) GetSuggestedActionJson() string {
	if x != nil {
		return x.SuggestedActionJson
	}
	return ""
}

type RecResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Recommendations []*Recommendation      `protobuf:"bytes,1,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RecResponse) Reset() {
	*x = RecResponse{}
	mi := &file_strategy_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecResponse) ProtoMessage() {}

func (x *RecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecResponse.ProtoReflect.Descriptor instead.
func (*RecResponse) Descriptor() ([]byte, []int) {
	return file_strategy_proto_rawDescGZIP(), []int{17}
}

func (x *RecResponse) GetRecommendations() []*Recommendation {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

var File_strategy_proto protoreflect.FileDescriptor

const file_strategy_proto_rawDesc = "" +
	"\n" +
	"\x0estrategy.proto\x12\bstrategy\"\xeb\x01\n" +
	"\aRuleDef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\x03R\taccountId\x12\x1d\n" +
	"\n" +
	"scope_json\x18\x04 \x01(\tR\tscopeJson\x12%\n" +
	"\x0econdition_json\x18\x05 \x01(\tR\rconditionJson\x12\x1f\n" +
	"\vaction_json\x18\x06 \x01(\tR\n" +
	"actionJson\x12\x1a\n" +
	"\bschedule\x18\a \x01(\tR\bschedule\x12\x1a\n" +
	"\bcooldown\x18\b \x01(\tR\bcooldown\"a\n" +
	"\x0fEvaluateRequest\x12'\n" +
	"\x05rules\x18\x01 \x03(\v2\x11.strategy.RuleDefR\x05rules\x12%\n" +
	"\x03ads\x18\x02 \x03(\v2\x13.strategy.AdContextR\x03ads\"\xc4\x01\n" +
	"\tAdContext\x12\x13\n" +
	"\x05ad_id\x18\x01 \x01(\x03R\x04adId\x12&\n" +
	"\x0fqianchuan_ad_id\x18\x02 \x01(\x03R\rqianchuanAdId\x12\x12\n" +
	"\x04cost\x18\x03 \x01(\x01R\x04cost\x12\x10\n" +
	"\x03roi\x18\x04 \x01(\x01R\x03roi\x12\x10\n" +
	"\x03ctr\x18\x05 \x01(\x01R\x03ctr\x12 \n" +
	"\vconversions\x18\x06 \x01(\x03R\vconversions\x12 \n" +
	"\vimpressions\x18\a \x01(\x03R\vimpressions\"\xa8\x01\n" +
	"\n" +
	"RuleAction\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\x03R\x06ruleId\x12\x13\n" +
	"\x05ad_id\x18\x02 \x01(\x03R\x04adId\x12\x1f\n" +
	"\vaction_type\x18\x03 \x01(\tR\n" +
	"actionType\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\x12\x1d\n" +
	"\n" +
	"value_type\x18\x05 \x01(\tR\tvalueType\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\"B\n" +
	"\x10EvaluateResponse\x12.\n" +
	"\aactions\x18\x01 \x03(\v2\x14.strategy.RuleActionR\aactions\"_\n" +
	"\x0fTestRuleRequest\x12%\n" +
	"\x04rule\x18\x01 \x01(\v2\x11.strategy.RuleDefR\x04rule\x12%\n" +
	"\x03ads\x18\x02 \x03(\v2\x13.strategy.AdContextR\x03ads\"\x8e\x01\n" +
	"\x10TestRuleResponse\x12.\n" +
	"\aactions\x18\x01 \x03(\v2\x14.strategy.RuleActionR\aactions\x12#\n" +
	"\rwould_trigger\x18\x02 \x01(\bR\fwouldTrigger\x12%\n" +
	"\x0etrigger_reason\x18\x03 \x01(\tR\rtriggerReason\"\xae\x01\n" +
	"\tAdMetrics\x12\x13\n" +
	"\x05ad_id\x18\x01 \x01(\x03R\x04adId\x12\x12\n" +
	"\x04cost\x18\x02 \x01(\x01R\x04cost\x12\x10\n" +
	"\x03roi\x18\x03 \x01(\x01R\x03roi\x12\x10\n" +
	"\x03ctr\x18\x04 \x01(\x01R\x03ctr\x12 \n" +
	"\vconversions\x18\x05 \x01(\x03R\vconversions\x12 \n" +
	"\vimpressions\x18\x06 \x01(\x03R\vimpressions\x12\x10\n" +
	"\x03cpa\x18\a \x01(\x01R\x03cpa\"<\n" +
	"\rMetricsWindow\x12+\n" +
	"\x06hourly\x18\x01 \x03(\v2\x13.strategy.AdMetricsR\x06hourly\"r\n" +
	"\x0eAnomalyRequest\x12-\n" +
	"\acurrent\x18\x01 \x03(\v2\x13.strategy.AdMetricsR\acurrent\x121\n" +
	"\ahistory\x18\x02 \x03(\v2\x17.strategy.MetricsWindowR\ahistory\"\xd5\x01\n" +
	"\aAnomaly\x12\x13\n" +
	"\x05ad_id\x18\x01 \x01(\x03R\x04adId\x12\x1f\n" +
	"\vmetric_name\x18\x02 \x01(\tR\n" +
	"metricName\x12#\n" +
	"\rcurrent_value\x18\x03 \x01(\x01R\fcurrentValue\x12\x1d\n" +
	"\n" +
	"mean_value\x18\x04 \x01(\x01R\tmeanValue\x12\x1b\n" +
	"\tstd_value\x18\x05 \x01(\x01R\bstdValue\x12\x17\n" +
	"\az_score\x18\x06 \x01(\x01R\x06zScore\x12\x1a\n" +
	"\bseverity\x18\a \x01(\tR\bseverity\"B\n" +
	"\x0fAnomalyResponse\x12/\n" +
	"\tanomalies\x18\x01 \x03(\v2\x11.strategy.AnomalyR\tanomalies\"Y\n" +
	"\x0ePredictRequest\x12\x13\n" +
	"\x05ad_id\x18\x01 \x01(\x03R\x04adId\x122\n" +
	"\n" +
	"history_7d\x18\x02 \x03(\v2\x13.strategy.AdMetricsR\thistory7d\"\x86\x01\n" +
	"\rROIPrediction\x12\x13\n" +
	"\x05ad_id\x18\x01 \x01(\x03R\x04adId\x12*\n" +
	"\x11predicted_roi_24h\x18\x02 \x01(\x01R\x0fpredictedRoi24h\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12\x14\n" +
	"\x05trend\x18\x04 \x01(\tR\x05trend\"L\n" +
	"\x0fPredictResponse\x129\n" +
	"\vpredictions\x18\x01 \x03(\v2\x17.strategy.ROIPredictionR\vpredictions\"\x99\x01\n" +
	"\n" +
	"RecRequest\x12\x15\n" +
	"\x06ad_ids\x18\x01 \x03(\x03R\x05adIds\x12<\n" +
	"\x0fcurrent_metrics\x18\x02 \x03(\v2\x13.strategy.AdMetricsR\x0ecurrentMetrics\x126\n" +
	"\n" +
	"history_7d\x18\x03 \x03(\v2\x17.strategy.MetricsWindowR\thistory7d\"\xc5\x01\n" +
	"\x0eRecommendation\x12\x13\n" +
	"\x05ad_id\x18\x01 \x01(\x03R\x04adId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x01R\n" +
	"confidence\x122\n" +
	"\x15suggested_action_json\x18\x06 \x01(\tR\x13suggestedActionJson\"Q\n" +
	"\vRecResponse\x12B\n" +
	"\x0frecommendations\x18\x01 \x03(\v2\x18.strategy.RecommendationR\x0frecommendations2\xef\x02\n" +
	"\x0fStrategyService\x12F\n" +
	"\rEvaluateRules\x12\x19.strategy.EvaluateRequest\x1a\x1a.strategy.EvaluateResponse\x12A\n" +
	"\bTestRule\x12\x19.strategy.TestRuleRequest\x1a\x1a.strategy.TestRuleResponse\x12F\n" +
	"\x0fDetectAnomalies\x12\x18.strategy.AnomalyRequest\x1a\x19.strategy.AnomalyResponse\x12A\n" +
	"\n" +
	"PredictROI\x12\x18.strategy.PredictRequest\x1a\x19.strategy.PredictResponse\x12F\n" +
	"\x17GenerateRecommendations\x12\x14.strategy.RecRequest\x1a\x15.strategy.RecResponseB1Z/github.com/example/qianchuan-saas/grpc/strategyb\x06proto3"

var (
	file_strategy_proto_rawDescOnce sync.Once
	file_strategy_proto_rawDescData []byte
)

func file_strategy_proto_rawDescGZIP() []byte {
	file_strategy_proto_rawDescOnce.Do(func() {
		file_strategy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_strategy_proto_rawDesc), len(file_strategy_proto_rawDesc)))
	})
	return file_strategy_proto_rawDescData
}

var file_strategy_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_strategy_proto_goTypes = []any{
	(*RuleDef)(nil),          // 0: strategy.RuleDef
	(*EvaluateRequest)(nil),  // 1: strategy.EvaluateRequest
	(*AdContext)(nil),        // 2: strategy.AdContext
	(*RuleAction)(nil),       // 3: strategy.RuleAction
	(*EvaluateResponse)(nil), // 4: strategy.EvaluateResponse
	(*TestRuleRequest)(nil),  // 5: strategy.TestRuleRequest
	(*TestRuleResponse)(nil), // 6: strategy.TestRuleResponse
	(*AdMetrics)(nil),        // 7: strategy.AdMetrics
	(*MetricsWindow)(nil),    // 8: strategy.MetricsWindow
	(*AnomalyRequest)(nil),   // 9: strategy.AnomalyRequest
	(*Anomaly)(nil),          // 10: strategy.Anomaly
	(*AnomalyResponse)(nil),  // 11: strategy.AnomalyResponse
	(*PredictRequest)(nil),   // 12: strategy.PredictRequest
	(*ROIPrediction)(nil),    // 13: strategy.ROIPrediction
	(*PredictResponse)(nil),  // 14: strategy.PredictResponse
	(*RecRequest)(nil),       // 15: strategy.RecRequest
	(*Recommendation)(nil),   // 16: strategy.Recommendation
	(*RecResponse)(nil),      // 17: strategy.RecResponse
}
var file_strategy_proto_depIdxs = []int32{
	0,  // 0: strategy.EvaluateRequest.rules:type_name -> strategy.RuleDef
	2,  // 1: strategy.EvaluateRequest.ads:type_name -> strategy.AdContext
	3,  // 2: strategy.EvaluateResponse.actions:type_name -> strategy.RuleAction
	0,  // 3: strategy.TestRuleRequest.rule:type_name -> strategy.RuleDef
	2,  // 4: strategy.TestRuleRequest.ads:type_name -> strategy.AdContext
	3,  // 5: strategy.TestRuleResponse.actions:type_name -> strategy.RuleAction
	7,  // 6: strategy.MetricsWindow.hourly:type_name -> strategy.AdMetrics
	7,  // 7: strategy.AnomalyRequest.current:type_name -> strategy.AdMetrics
	8,  // 8: strategy.AnomalyRequest.history:type_name -> strategy.MetricsWindow
	10, // 9: strategy.AnomalyResponse.anomalies:type_name -> strategy.Anomaly
	7,  // 10: strategy.PredictRequest.history_7d:type_name -> strategy.AdMetrics
	13, // 11: strategy.PredictResponse.predictions:type_name -> strategy.ROIPrediction
	7,  // 12: strategy.RecRequest.current_metrics:type_name -> strategy.AdMetrics
	8,  // 13: strategy.RecRequest.history_7d:type_name -> strategy.MetricsWindow
	16, // 14: strategy.RecResponse.recommendations:type_name -> strategy.Recommendation
	1,  // 15: strategy.StrategyService.EvaluateRules:input_type -> strategy.EvaluateRequest
	5,  // 16: strategy.StrategyService.TestRule:input_type -> strategy.TestRuleRequest
	9,  // 17: strategy.StrategyService.DetectAnomalies:input_type -> strategy.AnomalyRequest
	12, // 18: strategy.StrategyService.PredictROI:input_type -> strategy.PredictRequest
	15, // 19: strategy.StrategyService.GenerateRecommendations:input_type -> strategy.RecRequest
	4,  // 20: strategy.StrategyService.EvaluateRules:output_type -> strategy.EvaluateResponse
	6,  // 21: strategy.StrategyService.TestRule:output_type -> strategy.TestRuleResponse
	11, // 22: strategy.StrategyService.DetectAnomalies:output_type -> strategy.AnomalyResponse
	14, // 23: strategy.StrategyService.PredictROI:output_type -> strategy.PredictResponse
	17, // 24: strategy.StrategyService.GenerateRecommendations:output_type -> strategy.RecResponse
	20, // [20:25] is the sub-list for method output_type
	15, // [15:20] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_strategy_proto_init() }
func file_strategy_proto_init() {
	if File_strategy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_strategy_proto_rawDesc), len(file_strategy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_strategy_proto_goTypes,
		DependencyIndexes: file_strategy_proto_depIdxs,
		MessageInfos:      file_strategy_proto_msgTypes,
	}.Build()
	File_strategy_proto = out.File
	file_strategy_proto_goTypes = nil
	file_strategy_proto_depIdxs = nil
}
